### PR TITLE
[8.x] Explicitly set `chromedriver` port.

### LINKED ISSUE #1122: Failure with error message: Failed to connect to localhost port 9515 after 0 ms: Could not connect to server
### Dusk Version

8.2.4

### Laravel Version

11.21.0

### PHP Version

8.3.9

### PHPUnit Version

10.5.17

### Database Driver & Version

_No response_

### Description

After updating Laravel with `composer update`, Dusk fails with the following error message:
```
Failed to connect to localhost port 9515 after 0 ms: Could not connect to server
```

Running Dusk directly with `php artisan test -v --bail --group=browser` (instead from a `Makefile`) doesn't work either, unlike described [here previously](https://github.com/laravel/dusk/issues/1017#issuecomment-2233777328).

The update itself was intended to solve a prior problem when starting Dusk:
```
  session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 128.0.6613.85 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```
This problem occurred even after updating with `php artisan dusk:chrome-driver`:
```
ChromeDriver binary successfully installed for version 128.0.6613.84.
```
(and after restarting the computer).

### Steps To Reproduce

Update Chrome.

Then run:
```
composer update
php artisan dusk:chrome-driver
php artisan test -v --bail --group=browser
```
(Assuming that some test(s) belongs to group "browser".)

### LINKED ISSUE #1123: Not compatible with Chrome v128
### Dusk Version

8.2.4

### Laravel Version

11.21.0  

### PHP Version

8.3

### PHPUnit Version

11.1.3

### Database Driver & Version

_No response_

### Description

Fails to start with latest chrome version, Chrome 128

Tests\Browser\ExampleTest > basic example                                                                                                                                        WebDriverCurlException   
  Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","goog:chromeOptions":{"args":["--window-size=1920,1080","--disable-gpu"]}}}

### Steps To Reproduce

Fresh Laravel Installation
Update Chrome to 128

`php artisan dusk` fails

### PR DESCRIPTION
**Pull request by crynobone**
fixes #1123
fixes #1122

Before 128, ChromeDriver will use the default 9515 port, however this is no longer the case and would cause chromedriver to run on port 0. https://issues.chromium.org/issues/361370192

### CODE REVIEW

File: src/TestCase.php [hunk 1]
```diff
@@ -43,7 +43,8 @@ protected function setUp(): void
     protected function driver()
     {
         return RemoteWebDriver::create(
-            'http://localhost:9515', DesiredCapabilities::chrome()
+            $_ENV['DUSK_DRIVER_URL'] ?? env('DUSK_DRIVER_URL') ?? 'http://localhost:9515',
```
Comment (crynobone) [inline src/TestCase.php:46]: Replicate line from stub file:

https://github.com/laravel/dusk/blob/4e7666683d21290a72296b9aff4389262bed3261/stubs/DuskTestCase.stub#L43

**Comment by KieranLR** [comment]
fyi, this is the commit that confirms this is an intentional change in ChromeDriver behavior: https://chromium.googlesource.com/chromium/src/+/6f33d75f071e322c4a3e49b0a4ac2022e5b6cada
